spring.application.name=URL_Service1
server.port=8081

spring.datasource.url=jdbc:h2:file:./data/url_service1_db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

url.pool.low-watermark=500
url.pool.refill-batch-size=500
url.pool.seed-batch-size=5000
url.pool.code-length=6
url.pool.partition-start=0
url.pool.partition-end=e
