spring.application.name=RouterService
server.port=8080

router.normal-targets=http://localhost:8081,http://localhost:8082,http://localhost:8083,http://localhost:8084
router.partition-ranges=0-e,f-t,u-I,J-Z
router.partition-targets=http://localhost:8081,http://localhost:8082,http://localhost:8083,http://localhost:8084
